---
title: "Team_registration_and_proposal"
author: "linshan"
date: "2024-11-05"
output: github_document
---

#### Group members
Selina Hsuan (sh4354), Ghislaine Jumonville (gj2356), Carolyn Fish (csf2135), Camille Okonkwo (co2554), Sanika Sule (ss6692)
 
#### Project title
Getting to know Central Park’s Squirrels: An analysis of the demographic and behavioral patterns of NYC squirrels 

#### Motivation/ Statement of Purpose
Squirrels are familiar neighbors to all New Yorkers. Central Park provides over 800 acres of prime habitat for approximately 2,300 squirrels (roughly 2.74 squirrels per acre)^1^. Given the high prevalence of squirrels in New York City and their versatile role as friends, pests, vectors for diseases, such as rabies, and snacks to local predators, we aim to describe behavioral trends and spatial distribution of squirrel sightings in Central Park using 2018 Squirrel Census data^2^. 
 
#### Intended final product
A descriptive report of Central Park squirrel demography and behavior, including observed trends from our analyses. Results will also be shared via a GitHub hosted Webpage and a short explanatory video.  
 
#### Data sources
The 2018 Squirrel Census data is publicly available for download here: https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw. 
 
#### Analyses/ Visualizations
We anticipate our analysis of Central Park squirrels will generate: 

* **Table 1:** Squirrel demography table (fur color, age, fur highlight color)
* **Table 2:** Descriptive table of squirrel activity and time of survey (AM/PM, location, activity, vocalizations)
* **Figure 1:** A density cluster map of Central Park squirrel sightings (Central Park in whole, by zipcode, by community district)

*Additional figures will likely be derived from the descriptive tables to better demonstrate any interesting findings that we observe in the data.*

#### Coding challenges
We anticipate the data will require substantial cleaning and the ability to appropriately test significance in demographic, behavioral, or spatial distributions may be limited by small sample size. If the 2018 census sample is insufficient, we may have to bring in 2020 Squirrel Census data. Joining of these data sets may require additional tidying and research to ensure variables were reproducibly measured for each survey. 

#### Planned Timeline

* _09Nov23 - 17Nov23_: Proposal development 
* _18Nov23 - 26Nov23_: Exploratory analysis, table construction 
* _27Nov23 - 08Dec23_: Crunch Time (Write report, statistical analyses, final figure development)
* _09Dec23_: Project report, website, webcast, and team evals due 


#### Reference links
1. https://www.centralparknyc.org/articles/getting-to-know-central-parks-squirrels
2. https://www.thesquirrelcensus.com/data